Add bootstrap spinner
Omkaragrawal/CatchUpWeb pull request #67
Opened 2021-10-06 21:04 UTC by itzmeowww

2021-10-08 13:01 UTC, Omkaragrawal commented
Hey, I am glad you took up the task to add a bootstrap spinner. But unfortunately, you have changed the formatting a lot. I would recommend reformating the code in the format as before, where the HTML tag's properties are not on separate lines and the extra few lines are added in between the HTML tag.

@itzmeowww

2021-10-08 13:21 UTC, itzmeowww commented
@Omkaragrawal I have made some changes, please check it

2021-10-10 09:22 UTC, Omkaragrawal requested changes
I marked on last change that I want from you and then you are good to go.

2021-10-10 09:22 UTC, Omkaragrawal commented on index.html
> +    />
```suggestion
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self' data:; connect-src 'self' https://hacker-news.firebaseio.com https://corsenabled.herokuapp.com  https://*.hackerearth.com;script-src 'self' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com;" />
```

2021-10-10 09:28 UTC, Omkaragrawal commented on index.html
> +    />
@itzmeowww

2021-10-12 06:57 UTC, merged